### PR TITLE
Update bootlock.md with modified recovery image method

### PR DESCRIPTION
**Pull request by CoolPenguin27**
This pull request changes bootlock.md to mention that you can [modify a recovery image](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/workaround-for-battery-discharge-in-dev-mode/) to reapply the flags instead of installing ChromeOS again.

I'm not sure if this works if you leave Developer Mode.

### CODE REVIEW

**Comment by Apacelus** [comment]
Hmm, honestly I would rather set up a github workflow that creates those recovery images, instead of linking users to guides, even if the guides are official

**Comment by CoolPenguin27** [comment]
I could try making one

**Comment by CoolPenguin27** [comment]
kinda getting stale

**Comment by Apacelus** [comment]
As mentioned on the discord server, this pr should also remove any explanations about booting the secondary kernel as that is not needed anymore. Also, this pr should more clearly state what to do in such cases instead of "casually" mentioning it

**Comment by Apacelus** [comment]
Actually, no one had any NVRAM resets since we fixed the chromeos kernel, therefor I dont think we need this documentation anymore, at all. It might cause more confusion than its worth. Ill bookmark the website, in case anyone has an nvram reset.

**Pull request merged**
